sudo: required
dist: xenial

before_script:
  - git clone --depth 1 -b "v0.6.0" --single-branch https://github.com/k8s-school/kind-travis-ci.git
  - ./kind-travis-ci/kind/k8s-create.sh -s
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:

after_success:
  - echo "Push Supernnova image to Docker Hub"
