raw_dir: /Users/anaismoller/Science/SNPCC_data/SIMGEN_PUBLIC_DES
preprocessed_dir: /Users/anaismoller/Science/SuperNNova_general/SuperNNova_refactor/tests/snpcc/preprocessed
processed_dir: /Users/anaismoller/Science/SuperNNova_general/SuperNNova_refactor/tests/snpcc/processed
fig_dir: /Users/anaismoller/Science/SuperNNova_general/SuperNNova_refactor/tests/snpcc/figures
dump_dir: /Users/anaismoller/Science/SuperNNova_general/SuperNNova_refactor/tests/snpcc/rnn/vanilla_000

nb_epoch: 10000
nb_inference_samples: 1
batch_size: 128
batch_size_test: 16
learning_rate: 1.0E-3
min_lr: 1.0E-5
lr_factor: 0.5
patience: 1
data_fraction: 1.0
nb_classes: &nb_classes 2
raw_format: DAT
seed: 42
dataset: "photometry"
overwrite: True

module: vanilla_rnn
model:
  input_size: 11
  hidden_size: 16
  output_size: *nb_classes
  num_layers: 2
  dropout: 0
  embedding_dim: 16
  normalize: False

metadata_features:
  # - HOSTGAL_PHOTOZ
  # - HOSTGAL_PHOTOZ_ERR
