raw_dir: /home/tmain/Lyrebird/SuperNNova_refactor/raw
preprocessed_dir: /home/tmain/Lyrebird/SuperNNova_refactor/tests/dump/preprocessed
processed_dir: /home/tmain/Lyrebird/SuperNNova_refactor/tests/dump/processed
# fitopt_file: /home/tmain/Lyrebird/SuperNNova_refactor/raw/FITOPT000.FITRES
fig_dir: /home/tmain/Lyrebird/SuperNNova_refactor/tests/dump/figures
dump_dir: /home/tmain/Lyrebird/SuperNNova_refactor/tests/dump/rnn/vanilla_000

nb_epoch: 200
nb_inference_samples: 1
batch_size: 512
batch_size_test: 512
learning_rate: 1.0E-3
min_lr: 1.0E-5
lr_factor: 0.5
patience: 1
data_fraction: 1.0
nb_classes: &nb_classes 2
raw_format: FITS
seed: 42
dataset: photometry
overwrite: True
random_length: False

clf_weight: 0.

module: peak_rnn
model:
  input_size: 11
  hidden_size: 16
  output_size: *nb_classes
  num_layers: 2
  dropout: 0
  embedding_dim: 16
  normalize: False

metadata_features:
  - HOSTGAL_PHOTOZ
  - HOSTGAL_PHOTOZ_ERR
