raw_dir: /home/SuperNNova/tests/raw
preprocessed_dir: /home/SuperNNova/tests/dump/preprocessed
processed_dir: /home/SuperNNova/tests/dump/processed
fitopt_file: /home/SuperNNova/tests/fits/FITOPT000.FITRES
fig_dir: /home/SuperNNova/tests/dump/figures
dump_dir: /home/SuperNNova/tests/dump/rnn/vanilla_000

nb_epoch: 10
batch_size: 16
learning_rate: 1.0e-3
nb_classes: &nb_classes 2
raw_format: FITS
seed: 42
dataset: "saltfit"
overwrite: True

module: vanilla_rnn
model:
  input_size: 11
  hidden_size: 16
  output_size: *nb_classes
  num_layers: 2
  dropout: 0
  embedding_dim: 16
  normalize: True

metadata_features:
  - HOSTGAL_PHOTOZ
  - HOSTGAL_PHOTOZ_ERR
